name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: 저장소로 이동
      uses: actions/checkout@v2

    - name: Node.js 셋업
      uses: actions/setup-node@v2
      with:
        node-version: '20.10.0'

    - name: pnpm 설치
      run: npm install -g pnpm

    - name: 라이브러리 설치
      run: pnpm install

    - name: 빌드
      run: pnpm build

    - name: 배포
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git switch --orphan release
        mv dist/* .

        # gitignore 파일들 제거
        rmdir dist
        rm -rf node_modules
        rm -rf .next
        rm next-env.d.ts

        # _next 디렉토리가 무시되는 버그 수정을 위해 jeklly 비활성화
        touch .nojekyll

        git add .
        git commit -m "Release build from main branch"
        git push origin release --force
