name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: 저장소로 이동
      uses: actions/checkout@v2

    - name: Node.js 셋업
      uses: actions/setup-node@v2
      with:
        node-version: '20.10.0'

    - name: pnpm 설치
      run: npm install -g pnpm

    - name: 라이브러리 설치
      run: pnpm install

    - name: 빌드
      run: pnpm build

    - name: 배포
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        
        # 현재 브랜치에 dist 추가 및 임시 브랜치로 이동
        git checkout -b temp-branch
        git add -f dist/*
        git commit -m "temp"
        
        # release 브랜치로 체크아웃 (새로 만듦)
        git switch --orphan release
        
        # dist 폴더의 내용을 release 브랜치로 복사
        git checkout temp-branch -- dist
        mv dist/* .
        rmdir dist
        
        # 변경사항을 커밋 및 푸시
        git add .
        git commit -m "Release build from main branch"
        git push origin release --force
